### ISSUE TITLE
Missing null check on FileReader.result

### ISSUE THREAD

**Issue by marcomarsala** [Cerealkillerway/fileUploader#4]
You may get `Cannot read property 'substring' of null` in `fileUploader.js` on line 366:

Please find below a screenshot from Sentry:

![image](https://user-images.githubusercontent.com/5349718/55224344-99838b00-5210-11e9-901b-f564f7b73ae1.png)

**Comment by Cerealkillerway** [comment]
I see, it was not handling unsuccesful reading state; should be fixed in 3.7.3
